### ISSUE TITLE
Add support for Apex formatting using Prettier

### ISSUE THREAD

**Issue by muenzpraeger** [trailheadapps/dreaminvest-lwc#51]
**What is missing from the application? Please describe.**
The current project does not format Apex using [Prettier](https://prettier.io/).
    
**Describe the solution you'd like**
The [Apex Prettier Plugin](https://www.npmjs.com/package/prettier-plugin-apex) has to be implemented to format any Apex related file. That way it aligns with the formatting options in Developer Console.

**Comment by muenzpraeger** [comment]
@annyhe What's the status of this?

**Comment by annyhe** [comment]
@muenzpraeger Pull request out #77. Please review.
