### ISSUE TITLE
Trader Desktop tab: add ticker to Watchlist breaks Watchlist

### ISSUE THREAD

**Issue by annyhe** [trailheadapps/dreaminvest-lwc#60]
Components on the Trader Desktop tab are working until Add a ticker to a watchlist, for example use CRM. 
Then the entire page refreshes and the component disappears. It 
looks like this. Need to refresh the page again to see the original watchlists. The CRM ticker is not added to the watchlist.
<img width="856" alt="Screen Shot 2019-10-10 at 10 20 49 AM" src="https://user-images.githubusercontent.com/17040750/66591721-69665e80-eb48-11e9-8a4a-cef3296084c6.png">

**Comment by muenzpraeger** [comment]
What’s the proposed fix?
